"use client";

import * as React from "react";
import { generateTimeslots, type TimeslotGenerationConfig } from "timeslottr";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ConfigForm } from "./config-form";
import { Visualizer } from "./visualizer";
import { JsonOutput } from "./json-output";

export function Playground() {
  const [config, setConfig] = React.useState<TimeslotGenerationConfig>({
    day: new Date().toISOString().split("T")[0],
    range: { start: "09:00", end: "17:00" },
    slotDurationMinutes: 30,
    slotIntervalMinutes: undefined,
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 0,
    minimumSlotDurationMinutes: undefined,
    maxSlots: undefined,
    alignment: "start",
    includeEdge: true,
    excludedWindows: [],
  });

  const [slots, setSlots] = React.useState<any[]>([]);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    try {
      // Ensure required fields are present before generating
      if (!config.day || !config.range?.start || !config.range?.end || !config.slotDurationMinutes) {
        return;
      }

      // Deep clone or clean up config to avoid undefined/null issues if any
      const safeConfig = {
        ...config,
        // timezone: config.timezone || undefined, // timezone might be empty string
      };
      if (!safeConfig.timezone) delete safeConfig.timezone;

      const generated = generateTimeslots(safeConfig);
      setSlots(generated);
      setError(null);
    } catch (err) {
      console.error(err);
      setSlots([]);
      setError(err instanceof Error ? err.message : "An error occurred generating timeslots");
    }
  }, [config]);

  return (
    <div className="grid gap-12 lg:grid-cols-[1fr,1.5fr] items-start">
      <div className="space-y-6 lg:sticky lg:top-24">
        <ConfigForm config={config} onChange={setConfig} />
      </div>
      <div className="space-y-8">
        <div className="rounded-xl border bg-card text-card-foreground shadow-sm">
             <div className="flex flex-col space-y-1.5 p-6 pb-4 border-b">
                <h3 className="font-semibold leading-none tracking-tight">Generated Slots</h3>
                <p className="text-sm text-muted-foreground">Preview of the time slots based on your configuration.</p>
             </div>
             <div className="p-6 pt-4">
                 {error ? (
                  <div className="rounded-md bg-destructive/15 p-3 text-sm text-destructive">
                    {error}
                  </div>
                ) : (
                  <Visualizer slots={slots} timezone={config.timezone} />
                )}
             </div>
        </div>

        <div className="rounded-xl border bg-card text-card-foreground shadow-sm">
            <div className="flex flex-col space-y-1.5 p-6 pb-4 border-b">
                <h3 className="font-semibold leading-none tracking-tight">JSON Output</h3>
                <p className="text-sm text-muted-foreground">The raw data generated by the library.</p>
            </div>
             <div className="p-0">
                <JsonOutput data={slots} />
             </div>
        </div>
      </div>
    </div>
  );
}
